const data = {
  products: [
    {
      _id: '1',
      name: 'nike',
      slug: 'nike-slim-shirt-slug',
      category: 'Shirts',
      image: '/image/p1.jpg', //679px  x 829px
      price: 150,
      countInStock: 10,
      brand: 'Nike',
      rating: 5,
      numReviews: 7,
      description: 'high quality shirt',
    },
    {
      _id: '2',
      name: 'Adidas Fit shirt',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/image/p2.jpg',
      price: 65,
      countInStock: 0,
      brand: 'adidas',
      rating: 2,
      numReviews: 3,
      description: 'high quality shirt',
    },
    {
      _id: '3',
      name: 'cat Slim shirt',
      slug: 'cat-slim-shirt',
      category: 'Shirts',
      image: '/image/p3.jpg',
      price: 40,
      countInStock: 7,
      brand: 'puma',
      rating: 1,
      numReviews: 3,
      description: 'high quality shirt',
    },
    {
      _id: '4',
      name: 'Ss Slim shirt',
      slug: 'Sss-slim-shirt',
      category: 'Shirts',
      image: '/image/p4.jpg',
      price: 39,
      countInStock: 3,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 4,
      description: 'high quality shirt',
    },
  ],
};
export default data;
