const data = {
  products: [
    {
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/image/p1.jpg', //679px  x 829px
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviwes: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Fit shirt',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/image/p2.jpg',
      price: 65,
      countInStock: 5,
      brand: 'adidas',
      rating: 4.5,
      numReviwes: 10,
      description: 'high quality shirt',
    },
    {
      name: 'cat Slim shirt',
      slug: 'cat-slim-shirt',
      category: 'Shirts',
      image: '/image/p3.jpg',
      price: 80,
      countInStock: 7,
      brand: 'puma',
      rating: 4.5,
      numReviwes: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Ss Slim shirt',
      slug: 'Sss-slim-shirt',
      category: 'Shirts',
      image: '/image/p4.jpg',
      price: 39,
      countInStock: 3,
      brand: 'Nike',
      rating: 4.5,
      numReviwes: 4,
      description: 'high quality shirt',
    },
  ],
};
export default data;
